### ISSUE TITLE
Forced reflow causing slow rendering with many DOM elements

### ISSUE THREAD

**Issue by kaikue** [google/neuroglancer#166]
With many elements in the DOM, there is a noticeable slowdown when rotating the 3D view. Profiling in Chrome suggests that this is caused by forced reflow:
![image](https://user-images.githubusercontent.com/2455512/66600944-b5c79380-eb74-11e9-8a69-7d4296f734b1.png)
Chrome points to line 167 of display_context.ts.

The relevant code in `draw()`:
```
    canvas.width = canvas.offsetWidth;
    canvas.height = canvas.offsetHeight;
    this.canvasRect = canvas.getBoundingClientRect();
```
These three lines can all force layout reflow, according to this guide: https://gist.github.com/paulirish/5d52fb081b3570c81e3a

In particular, see this comment: https://gist.github.com/paulirish/5d52fb081b3570c81e3a#gistcomment-1585116
> While all reads can happen where needed (but never inside a rAF) any DOM writes should happen inside a rAF.

`draw()` is in fact inside a rAF (requestAnimationFrame), since it is called by `update()`, which is in a `requestAnimationFrame`. That discussion suggests that this is bad practice, and could be cause of this slowdown. It seems like those layout-reading lines should be moved outside `requestAnimationFrame` into a separate task.

**Comment by jbms** [comment]
I think the canvas should not actually be changing in size except when the browser window resizes (unless you are doing some sort of custom embedding of neuroglancer in another webpage).  However, I suppose it is possible that due to some layout interaction the browser has to do a full reflow to figure that out.

Currently, the callback passed to resizeObserver doesn't actually do anything with the sizes, and just defers the work until the redraw.  It seems like potentially this issue could be solved by checking in the resizeObserver callback if the canvas element is one of the elements that has been resized, and if so, updating the canvas width and height, and caching the canvasRect.

However, I would think that setting canvas.width and canvas.height should not force reflow, because that just affects the size of the framebuffer, not the actual layout of the element.  canvas.width is independent of canvas.style.width.  Maybe there is some interaction I'm not thinking of, or maybe this is just a chrome bug.

If you have chance to look into these possibilities, I would be very interested in what you find.

**Comment by kaikue** [comment]
Setting canvas.width and canvas.height won't force reflow, but getting canvas.offsetWidth and canvas.offsetHeight will. I'll try moving those outside of draw() and see if that helps.

**Comment by kaikue** [comment]
Moving all the offsetWidth, clientLeft, etc. calls outside of draw() does indeed help quite a bit. The bottlenecks in the profiler are gone, and it renders noticeably faster.
![image](https://user-images.githubusercontent.com/2455512/66607149-971bc980-eb81-11e9-9734-02f2298525f7.png)

You can see my changes here: https://github.com/seung-lab/neuroglancer/commit/3cf9ad3e20019652875062d892eeafd3f3b3dc73

This code has a few minor issues (I don't know if scheduleRedraw is actually the best place to put this, and I think it tries to draw an invalid framebuffer on the first frame), but it shows the improvement from moving these reflow-forcing properties and methods outside of requestAnimationFrame. There were a few in rendered_data_panel.ts that I changed as well.

**Comment by kaikue** [comment]
Upon further review, I'm not sure those changes really help much:
![image](https://user-images.githubusercontent.com/2455512/66757710-bc9f2080-ee6a-11e9-895b-7000ddd43264.png)

There is still some forced reflow (caused by layer.ts:818 recursively calling scheduleRedraw inside requestAnimationFrame) but it looks like it would still be limited by regular layout, since there are just too many elements in the DOM, and I don't think that can be sped up without just removing a bunch of the elements. I'm not sure if fixing this is worth it.
