### ISSUE TITLE
Tiles from "render" datasource not being loaded

### ISSUE THREAD

**Issue by perlman** [google/neuroglancer#180]
Data is no longer loading from render data sources (as of 3db0fa6b46d72aeac0ea71412d8ab62ead328efb).

The stack metadata is loaded (/stacks/), along with URL auto-completion works, and but no tile data is being loaded. There are no errors on the console.

I am slowly going through the changed code, but have not yet found anything obvious. (I suspect it's something simple, along the lines of metadata from render not being stored correctly?)

![image](https://user-images.githubusercontent.com/671841/70062065-5ce40c80-15b3-11ea-9a0f-c2e4232de684.png)

**Comment by jbms** [comment]
Sorry about that.  I don't have a convenient way to run a render server so I wasn't able to test the changes.  I see that the lowerClipBound and upperClipBound are computed incorrectly --- they should be in downsampled voxels, not nanometers.  But I'm not sure if that is the only problem.  If you can provide me with access to a render server I can try to debug it --- otherwise I suggest printing the result of getSources.

**Comment by jbms** [comment]
I fixed the clip bounds issues in 54c3be84b6cafd0328ace5b78fecf66b1ad335d0 but I'm not sure if that will solve this problem.

**Comment by perlman** [comment]
That helps -- I now see correct limits and associated bbox in the viewer -- but still no tile requests.
 
I'll poke around & try to figure out where to spawn an temporary render instance.

**Comment by perlman** [comment]
Fixed! Thanks @jbms!
