### ISSUE TITLE
Pixel values for subsequent subsources display as NULL

### ISSUE THREAD

**Issue by chrisroat** [google/neuroglancer#182]
I love the new subsources -- I will find these immensely useful.  Are there practical limitations, besides browser url limits, if I wanted, say, hundreds of subsources on several layers?

My actual bug report is that the pixel values are not being displayed when mousing over a subsource beyond the first one.   I'd include a screenshot, but the mouse isn't visible in it.  Let me know if you can't reproduce it, and I can provide more details.

**Comment by jbms** [comment]
Thanks for reporting this.

Note: The terminology I intended is that a layer can have multiple "data sources", each specified by a "data source URL".  A given "data source" can have multiple related "subsources" (e.g. volume data, meshes, skeletons, bounds) all sharing a common coordinate space.  Of course this terminology is not too clear due to the lack of documentation.

I assume that you want to use many data sources specifying non-overlapping volumes within a single layer ([perhaps separate bounding boxes, or separate slices in a stack)?

Right now multiple data sources in a single layer is rendered essentially the same as having each data source in a separate layer.  There isn't any spatial indexing across data sources, so even if a data source is not visible, some amount of work is required per data source each frame to determine that.  I haven't tested the practical limits, though.  Possibly spatial indexing could be implemented to speed that up.

**Comment by chrisroat** [comment]
Yes, my use case is non-overlapping volumes.  I'm actually considering merger them into one cloudvolume, as they have the same coordinate system and resolution.  But for now, discovery of this feature was a pleasant surprise!
