### ISSUE TITLE
Data not rendered in perspective view in the single-panel mode

### ISSUE THREAD

**Issue by tingzhao** [google/neuroglancer#188]
In the latest version (commit 9dd984ba08f39ff3333cffa68ee5751f510280d2), when I switched from the following 4-panel view:
![image](https://user-images.githubusercontent.com/2903167/71128756-f4547c80-21bb-11ea-94a1-c726009d5421.png)

to the single-panel view, all the rendered data (grayscale, segmentation, skeletons, ...) were gone in the perspective view:

![image](https://user-images.githubusercontent.com/2903167/71128825-21a12a80-21bc-11ea-9c63-bbb52ab687c3.png)

**Comment by jbms** [comment]
Skeletons and meshes for selected objects should be visible.  However, it is expected that cross sections are not visible when in the 3d-only view.

This is really just a UI limitation --- in the 4 panel or 2 panel views, the width and height of the cross sections shown in the 3d view exactly match the width and height of the corresponding cross section panel.  In the 1-panel 3d view, since there are no cross section panels, that method of choosing the width and height doesn't work, so I just don't show cross sections at all.

In fact, you can still force cross sections to be displayed in the 3d view by modifying the JSON state directly:

 "layout": {
    "type": "3d",
    "crossSections": {
      "a": {
        "width": 1024,
        "height": 1024
      }
    }
  }

https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B3019.417724609375%2C3133.125732421875%2C3998.703125%5D%2C%22crossSectionScale%22:3.762185354999915%2C%22projectionOrientation%22:%5B-0.4099641740322113%2C0.11453622579574585%2C0.6523764729499817%2C-0.6270691752433777%5D%2C%22projectionScale%22:4593.980956070106%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://neuroglancer-public-data/flyem_fib-25/image%22%7D%2C%22blend%22:%22default%22%2C%22name%22:%22image%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://neuroglancer-public-data/flyem_fib-25/ground_truth%22%7D%2C%22segments%22:%5B%22158571%22%2C%2221894%22%2C%2222060%22%2C%2224436%22%2C%222515%22%5D%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines_and_points%22%2C%22mode3d%22:%22lines%22%7D%2C%22name%22:%22ground-truth%22%7D%5D%2C%22showSlices%22:false%2C%22layout%22:%7B%22type%22:%223d%22%2C%22crossSections%22:%7B%22a%22:%7B%22width%22:1024%2C%22height%22:1024%7D%7D%7D%7D

**Comment by tingzhao** [comment]
That makes sense. Thank you for the explanation and hint!

**Comment by stuarteberg** [comment]
@jbms thanks for the example above.  I can't figure out how to select the orientation of the cross-section that is shown.  I see in the code there is an `orientation` member, but setting it to a quaternion in the JSON state is apparently not valid.  Is there a way to set the position and orientation of the cross section?

(I'm interested in making a movie using the `video_tool` that uses the `3d` layout but nonetheless displays a cross-section.)

**Comment by jbms** [comment]
> [@jbms](https://github.com/jbms) thanks for the example above. I can't figure out how to select the orientation of the cross-section that is shown. I see in the code there is an `orientation` member, but setting it to a quaternion in the JSON state is apparently not valid. Is there a way to set the position and orientation of the cross section?
> 
> (I'm interested in making a movie using the `video_tool` that uses the `3d` layout but nonetheless displays a cross-section.)

Use `{"link": "unlinked", "value": quat}`

**Comment by stuarteberg** [comment]
Thanks, @jbms!  That works.
