### ISSUE TITLE
n5 on s3

### ISSUE THREAD

**Issue by d-v-b** [google/neuroglancer#189]
I have N5 data stored on S3 in [this bucket](https://s3.amazonaws.com/janelia.hhmi.org-cosem-dev). CORS is set up to allow GETs from everywhere, but it looks like bucket is not readable as N5 by neuroglancer (I get http error 0 when I point neuroglancer to n5://https://{bucket}/{dataset}. If N5 via S3 is supported, how should I troubleshoot this?

Thanks!

**Comment by jbms** [comment]
I haven't tested it, but it should be possible to make it work easily enough.  To enable file name completion work a small amount of work would be needed to recognize s3 URLs --- the S3 listing API is already being used in Neuroglancer for name completion for GCS.

With: n5://https://s3.amazonaws.com/janelia.hhmi.org-cosem-dev/data as a neuroglancer datasource I get 403 forbidden, which I also get when trying to access:

https://s3.amazonaws.com/janelia.hhmi.org-cosem-dev/data/attributes.json

It looks like the files aren't publicly readable even though listing seems to work.

Currently auth is not supported, so only publicly accessible buckets will work.  

I was planning to add support for JWT-based authentication for GCS (you would need to create service account, give it read access to the bucket, then create a JWT for that service account with an oauth scope of https://www.googleapis.com/auth/devstorage.read_only (and optionally a time limit), then use a URL like:
n5+gs+jwt-XXXXXXXXXXXX://...

Anyone you give the neuroglancer link to gets access to the service account with https://www.googleapis.com/auth/devstorage.read_only permission, so you would want to ensure the service account only has a limited set of permissions.

Not sure if S3 supports a similar authentication method.

**Comment by d-v-b** [comment]
The entire contents of the bucket should now be publicly readable, (and the goal here is to use public data, so hopefully auth issues are orthogonal). Despite the permissions, I still get http error 0 when I try to add it as a datasource. Where are you seeing the 403 error?

**Comment by jbms** [comment]
When using

n5://https://s3.amazonaws.com/janelia.hhmi.org-cosem-dev/data

as the datasource URL, the problem is that neuroglancer attempts to retrieve attributes.json files in all parent directories as well, in accordance with n5 attribute inheritance.

So it tries to retrieve

https://s3.amazonaws.com/janelia.hhmi.org-cosem-dev/data/attributes.json
https://s3.amazonaws.com/janelia.hhmi.org-cosem-dev/attributes.json
https://s3.amazonaws.com/attributes.json

The last URL returns 404 but without appropriate CORS headers.

Neuroglancer could just treat the unknown error 0 the same as 404, but I'm not sure that is ideal.  It might be better for Neuroglancer to specifically detect s3 URLs.

Using a subdomain style S3 URL like

n5://https://janelia.hhmi.org-cosem-dev.s3.amazonaws.com/data

should work around this problem.  Unfortunately, there seems to be a TLS certificate problem when using the subdomain URLs --- both Chrome and Firefox return ERR_CERT_COMMON_NAME_INVALID.  I think this may be due to the fact that the bucket name contains a dot.  However, if you connect without TLS (which only works from either a localhost neuroglancer instance, or http://neuroglancer-demo.appspot.com, not from https://neuroglancer-demo.appspot.com), it works:

http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-9%2C%22m%22%5D%7D%2C%22position%22:%5B62.427223205566406%2C57.02953338623047%2C64%5D%2C%22crossSectionScale%22:0.5886049696783552%2C%22projectionScale%22:128%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://http://janelia.hhmi.org-cosem-dev.s3.amazonaws.com/data%22%7D%2C%22tab%22:%22source%22%2C%22blend%22:%22default%22%2C%22name%22:%22data%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22data%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D

**Comment by d-v-b** [comment]
That's good to know; the link did indeed work for a neuroglancer instance running on localhost. But I managed to break things again by putting my N5 container inside a folder within the bucket (the purpose of this is to store a human-readable summary document in the same bucket as the n5 container, or to store multiple n5 containers in a single bucket).  

From a practical perspective, what would you recommend I do here? It looks like getting the s3/*/n5 pattern working smoothly requires some tweaks in neuroglancer, whereas if I used a [proxy](https://github.com/perlman/n5ng) that served those files in precomputed format then I could get everything working on my own.

**Comment by jbms** [comment]
Not sure I understand the problem.  It looks like you moved the data to

sample1.n5/data but after updating the data source URL to

n5://http://janelia.hhmi.org-cosem-dev.s3.amazonaws.com/sample1.n5/data

it works fine for me:

http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-9%2C%22m%22%5D%7D%2C%22position%22:%5B64%2C64%2C64%5D%2C%22crossSectionScale%22:0.5886049696783552%2C%22projectionScale%22:128%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://http://janelia.hhmi.org-cosem-dev.s3.amazonaws.com/sample1.n5/data%22%7D%2C%22tab%22:%22source%22%2C%22blend%22:%22default%22%2C%22name%22:%22data%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22data%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D

**Comment by d-v-b** [comment]
You're right, everything is working after changing the bucket structure. (I'm not sure what I was doing wrong on my end).

Do you have any ideas for handling the TLS issue? I'll look into creating a bucket name without a dot in it.

**Comment by d-v-b** [comment]
Viewing data from bucket with a dot-free name doesn't seem to work with TLS: 
see 
https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-9%2C%22m%22%5D%7D%2C%22crossSectionScale%22:0.5886049696783552%2C%22projectionScale%22:128%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://http://janelia-cosem-dev.s3.amazonaws.com/sample1.n5/data%22%7D%2C%22tab%22:%22source%22%2C%22blend%22:%22default%22%2C%22name%22:%22data%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22data%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D

vs the http version

**Comment by jbms** [comment]
When using non-localhost neuroglancer client, the datasource URL must use TLS if, and only if, the neuroglancer client URL uses TLS.  In the link in your prior message, the datasource URL is still http://.

Avoiding dots is the simplest workaround, but if you would like to make some (relatively easy) changes to Neuroglancer to make things more convenient, there are a few options (all of which might be useful):

1. Neuroglancer could be extended to support something like s3:// URLs (slightly trickier than for GCS because there are multiple s3 regions and you can't just use s3.amazonaws.com for all regions).  This would also allow completion to work.

2. The N5 parent directory traversal could specifically detect path-style S3 bucket URLs

3. The N5 parent attributes.json lookup could treat an unknown error 0 the same as 404.
