### ISSUE TITLE
Exploring the idea of raster (pixel-perfect) annotations

### ISSUE THREAD

**Issue by Tomaz-Vieira** [google/neuroglancer#216]
Hello,

#### Context
I work on a software called "ilastik", which, amongst other things, does image classification and segmentation. We're experimenting with using neuroglancer as a viewer for the web version of ilastik. The most basic workflow is:

1 - loading you data;
2 - label some parts of your data with different colors in order to train the pixel classifier;
3 - Wait for ilastik to predict which pixels of your image correspond to each label.

Labeling data in the desktop version of ilastik is done using brush strokes, which produce pixel-perfect annotations. The annotations in neuroglancer, on the other hand, are vector data.

I've managed to extend neuroglancer's annotation tools and add a "brush stroke" tool, which produces a sequence of line segments, and that somewhat behaves like a raster brush tool. There are some obvious problems, though, in that:

- I need to rasterize those sequences of line segments into integer coordinates;
- dealing with brush thickness is tricky;
- (de)serializing is very awkward; it doesn't feel right to serialize the very data-dense brush strokes into the URL, though I can keep those in the backend;
- An eraser tool would be very hard to accomplish in this scheme;

#### Question
Would you have any ideas or recommendations on implementing raster annotations with neuroglancer? So far I'm thinking that the best strategy would be to use neuroglancer strictly as a viewer, build a raster annotation tool on top of it, and then serve the brush strokes as a DataSource. On the other hand, as awkward as it was to force a vector-brush into raster pixels, it gave me all the advantages of Neuroglancer's builtin annotation tools, like color picking, snapping to position and deletion, which would be a shame to lose.

Thank you for your time,
Tomaz

**Comment by jbms** [comment]
This is certainly an often-requested feature and if you implement it I'm sure it will be useful to many people.

I think it would make sense to extend the existing MultiscaleVolumeChunkSource interface to support a new read-write data source, where locally modified chunks would store a boolean mask array in addition to the modified values to indicate which positions have been updated.  Then these modifications could be sent back to the server either automatically or upon an explicit commit action.

Handling multi-resolution and undo would add additional challenges, though.

Alternatively you could try to just handle all brush strokes server side and then just have neuroglancer reload the relevant chunks.  At the moment neuroglancer doesn't really support this sort of low-latency interaction through the python integration or even per-chunk invalidation but maybe it could be made to work.

What representation does ilastik normally use for these brush strokes?

**Comment by Tomaz-Vieira** [comment]
We keep the strokes in  something like a sparse array. We dynamically create grid-aligned tiles as the user draws, and fill those tiles with the pixels marked by the brush strokes. For our use case, we expect there to be only  few brush strokes, since the classifier doesn't need a lot of samples. This way we can easily support an eraser tool but we don't support undo-redo, though, and that is dearly missed. We also don't handle multi-resolution, and it's hard to tell what would be sensible to do in that case.

The idea of implementing a read/write MultiscaleVolumeChunkSource is pretty interesting. Is there any implementation of a client-side ChunkSource in Neuroglancer? This could potentially help us in another case, which is to allow a user to use ilastik to classify images that are not accessible on the internet, by loading them into the neuroglancer client, though I'd have to think of the consequences of doing something like that.

Serialization would still be weird, though. It seems all annotations serialize to the URL, but that probably wouldn't work for brush strokes, so it would need some special-case to either save the brush strokes to local storage or to a server backend.

**Comment by jbms** [comment]
I assumed that neuroglancer would be connected to a running ilastik process, which could be responsible for serving the data and storing the annotations.  Is that not correct --- do you want to instead move everything in ilastik into the web browser?

I think serializing to the URL wouldn't work well due to the size of the data.  Local storage might work but I'm not inclined to trust it for anything other than a cache.

The existing annotations interface does actually support read-write server-side annotations on our internal Google brainmaps api data source, and flyem has also added support for the dvid data source which they are working to upstream.  I imagine a similar approach could be used for read-write volumetric data.

**Comment by Tomaz-Vieira** [comment]
Your assumption was correct, there should always be a running ilastik server, and we don't plan to have a js implementation of ilastik any time soon. I was just thinking of some edge cases where a user might want to use web ilastik without having to upload sensitive data to the internet, and it occurred to me that perhaps it would be possible to have the client-side ChunkSource stream the local data to the server, but that's so secondary it doesn't merit a discussion right now =)

I will have a look at the current implementations of read-write server-side annotations and see if I can come up with something sensible

**Comment by Tomaz-Vieira** [comment]
Hello,

I finally had some time to look into this again, and I have a prototype that can draw pixel-perfect (or, rather, voxel-perfect) brush strokes. It's built as an overlay, so that it can be applied to any viewer, but I really would like to validate it with Neuroglancer. Right now I'm having some trouble keeping it in sync with Neuroglancer and its many views; maybe you could point me in the right direction. I'm looking for a `position_in_world_coords: vec3` and an `orientation: quat` that I can programmatically get and apply to my camera every time `Viewer.navigationState` changes.

I thought `Viewer.navigationState.pose` would have everything I need, but I'm finding it hard to interpret its meaning. Apparently `DisplayPose.position` is the camera's position (or, I guess, the "Sections" intersection), expressed in "Voxel coordinates" (as opposed to in "World coordinates"). Is it safe to assume that `DsplayPose.orientation` is also expressed in the Voxels coordinate system?
I find the coo

**Comment by jbms** [comment]
Exciting progress --- I'd be interested to take a look once you have an integration.

The coordinate transformations in Neuroglancer are unfortunately somewhat complicated.  The actual projection for sliceview (cross-section views) is computed here:

https://github.com/google/neuroglancer/blob/add6885da32498a1cfd1075a4c19aae8ffb5a6f2/src/neuroglancer/sliceview/frontend.ts#L152

For a given sliceview, you can access `sliceview.projectionParameters.value` to get access to the SliceViewProjectionParameters / ProjectionParameters:

https://github.com/google/neuroglancer/blob/add6885da32498a1cfd1075a4c19aae8ffb5a6f2/src/neuroglancer/sliceview/base.ts#L226

https://github.com/google/neuroglancer/blob/add6885da32498a1cfd1075a4c19aae8ffb5a6f2/src/neuroglancer/projection_parameters.ts#L23

Unfortunately the comments are not great, but "world coordinates" means voxels in the global coordinate space (but only the selected "display dimensions", i.e. the ones shown on the left side of the panel in red/green/blue).

It isn't guaranteed that you can decompose the viewProjectionMat (which maps from global voxel space to OpenGL clip space) into a quaternion, offset, scale --- it would be better to just work with the transform matrices directly.

If you can integrate your overlay by defining a SliceViewPanelRenderLayer (and drawing the overlay in its `draw` method using WebGL), that would be simplest because then it will automatically be called for each slice view panel with appropriate rendering parameters and WebGL framebuffer provided.

Otherwise, I suppose you can try to hook into sliceview panel creation some other way, and then use the fields of RenderedPanel:

https://github.com/google/neuroglancer/blob/add6885da32498a1cfd1075a4c19aae8ffb5a6f2/src/neuroglancer/display_context.ts#L81

to map from OpenGL clip coordinates to screen coordinates.

**Comment by Tomaz-Vieira** [comment]
Thanks for the quick response =) Unfortunately it took me a a while to get through it all, but it was great having a clue of where to look for stuff.

In the end I went with something like this:
```typescript
    let voxel_to_world = mat4.fromScaling(mat4.create(), vec3.fromValues(1, -1, -1))

```

https://drive.google.com/file/d/1QRw1s6khVkxRniG_1abDJQwaBarkYp9_/view?usp=sharing

**Comment by Tomaz-Vieira** [comment]
Thanks for the quick response =) Unfortunately it took me a a while to get through it all, but it was great having a clue of where to look for stuff.

In the end I managed to derive a `location_w` and `orientation_w` with something like this:
```typescript
//flip y and x so y points up and -z goes int the screen when the camera is reset
let voxel_to_world = mat4.fromScaling(mat4.create(), vec3.fromValues(1, -1, -1))
let pos_vx = viewer.navigationState.pose.position.value as vec3;
let camera_pos_w = vec3.transformMat4(vec3.create(), pos_vx, voxel_to_world)

let camera_orientation_vx: quat = viewer.navigationState.pose.orientation.orientation
const rotation_axis_vx = vec3.create();
const rotation_rads = quat.getAxisAngle(rotation_axis_vx, camera_orientation_vx)
const rotation_axis_w = vec3.transformMat4(vec3.create(), rotation_axis_vx, voxel_to_world);
const camera_orientation_w = quat.setAxisAngle(quat.create(), rotation_axis_w, rotation_rads)

overlay.snapTo(camera_pos_w, camera_orientation_w)
overlay.setZoom(1 / viewer.navigationState.zoomFactor.value)

```
And here's a [video](
https://drive.google.com/file/d/1QRw1s6khVkxRniG_1abDJQwaBarkYp9_/view?usp=sharing) of how it's looking right now.

The project is a standalone overlay, and is hosted [here](https://github.com/ilastik/webilastik-overlay) if you want to take a look. This allows it to be used with arbitrary viewers by providing some glue code like the one above. I plan to integrate it with ilastik soon, but I'll leave the ilastik logic well separated from the brushing logic (maybe in a separate, standalone library).

**Comment by stuarteberg** [comment]
@Tomaz-Vieira This work is exciting (and so is your general work with ilastik :-)

Is there any hope that your brushing overlay could be somehow integrated with neuroglancer's existing Python API?  If someone wanted to start down that path, do you have any advice for them?
