### ISSUE TITLE
Displaying segment boundaries only in cross section view

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#239]
I have some use cases where I am interested in showing only a single color (e.g. black or white) boundary between segments with the internal part of the segment transparent such that an image layer underneath is fully unobscured. Something like the left half of this figure (without the text labels): https://www.spandidos-publications.com/article_images/mmr/19/4/MMR-19-04-3045-g00.jpg. This is essentially what the 3d mesh is, but I am looking for this functionality in 2d. This doesn't seem possible by tweaking the colors/opacity of a segmentation layer because the boundary is only an illusion arising from the fact that adjacent segments are different colors. 

I wonder whether this has come up before and for example if there are other data sources that could supports this? I could see extending the annotation layers to support polygons and using those to define the boundaries as an option if this is not already implemented.

**Comment by austinhoag** [comment]
OK thanks I think I understand what you are suggesting. I am new to the shader language and while there seem to be good resources out there, I have some questions as I try to implement something like this. One difficulty I have is I cannot log out the value of a variable in the shader code. Do you have any tips for overcoming this? I have SHADER_DEBUG=true set in `src/neuroglancer/webgl/shader.ts` so that helps me identify an error and see the shader code altogether, but it isn't able to log variable values from what I can tell.

For the initial pass, it's not clear to me what a "texture" is and how I would render the segmentation map to one of these. As far as I can tell, I can get the value at each position in the segmentation map using getDataValue(). I have tested rendering these values in `src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts` via:
```
fragmentMain += `
  // emit(vec4(mix(vec3(1.0,1.0,1.0), rgb, saturation), alpha)); // your existing code
  emit(vec4(toNormalized(getDataValue()),toNormalized(getDataValue()),toNormalized(getDataValue()), alpha)); // code I added
`;
```
This shows me a grayscale map of my segmentation layer. It's not clear to me where to go from here since what I really want is a 2D map of my segmentation values and the coordinates at each pixel so that I can run a function as per your suggested second pass. I'm not sure how to get that.

**Comment by jbms** [comment]
The approach I suggested will definitely take a bit of work, and will probably require you to first learn a bit about WebGL/OpenGL.  I'd suggest going through a tutorial (maybe https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial) to get up to speed.  You'll also find it useful if you intend to do graphics programming in the future, as even if it isn't WebGL there are a lot of commonalities.

A texture is essentially a 2-d array that lives in GPU memory.  They can also be 3d and have some extra functionality and optimizations, but that isn't relevant for this purpose.  Shader code can read from textures via random access.  Shader code can also write to textures, but only by rendering to them.  Rendering to a texture means rendering to a framebuffer with textures bound to the "color attachments".  In fact Neuroglancer already does this, via webgl/offscreen.ts when rendering the cross-section views --- you would just need to render to a different texture.  The closest thing currently in Neuroglancer to what you want to do is in perspective_view/panel.ts, where transparency is handled by rendering to separate textures specified by transparentConfiguration, and then transparencyCopyHelper is used to transform and copy those textures into the main framebuffer.  "Copy" actually just means rendering two triangles that cover the entire framebuffer with a special shader that performs the desired transformation.  That is a common trick.

As for debugging shaders, it can indeed be a bit challenging because there is no way to print.  The only way to get information out of a fragment shader is by writing it to one of the normal outputs.  You could bind an extra color attachment to use as a debugging channel but that is kind of a pain.  Often the easiest thing, though, is "color-based debugging": just output one of several colors to indicate one of several possible values.

Neuroglancer does include fragmentShaderTest, which is used in the unit tests to test shader code.  See e.g. gpu_hash/shader.spec.ts.  fragmentShaderTest makes it easy to output values of various types from shader code directly without needing to go through a lot of trouble.

**Comment by austinhoag** [comment]
I'm actually starting to think this approach is not going to serve my group's needs. I was able to get a demo of this working using a PNG of a small section of segmentation map as a texture and running a simple edge detector on that. This is the texture representing the original segmentation map:
![segmap_texture](https://user-images.githubusercontent.com/42473349/95774123-cd58c100-0c8d-11eb-80b7-196966de37dc.png)
and this is after edge detection:
![screenshot_boundaries](https://user-images.githubusercontent.com/42473349/95774153-de093700-0c8d-11eb-8ab3-b8c184ac1cc2.png)

The boundaries are too noisy to be figure-worthy. I imagine there is some additional filter I could apply at this point, but I have not found a good one yet. I tried a gaussian blur on the original image before edge detecting to dampen down the noise, but that doesn't really help. What I really want are as straight lines as possible at the boundaries -- essentially a vectorized drawing. Do you have any suggestions for implementing something like this in Neuroglancer? 

I have also thought about making an annotation layer for each 2D slice, but I think there I might have the same problem. I have not seriously tried this yet to see how it would come out.

**Comment by jbms** [comment]
If I understand correctly, your segmentation is fairly low resolution and you want the edges shown to be smoother than what is actually in the segmentation?

One option is to create a higher-resolution segmentation with smoother edges.

For the edge detection, potentially if you upsample then gaussian blur you will get smoother edges.  (With the approach I was suggesting, the upsampling would happen automatically if you zoom in, since the edge detection would happen at screen resolution, not the original data resolution; it would be possible to do gaussian blurring in Neuroglancer.)  Just blurring without upsampling won't be able to smooth out the edges.

**Comment by austinhoag** [comment]
What do you mean by "zoom in" and "upsample" here?

**Comment by jbms** [comment]
By zoom in, I mean displaying the segmentation sufficiently "zoomed in" such that 1 voxel of the segmentation data is larger than 1 screen pixel.  By upsample, I mean rescale to a higher resolution, e.g. a 2x2x2 patch in the upsampled version might all have the same segment id corresponding to a single voxel in the original version.

**Comment by austinhoag** [comment]
I ended up

**Comment by austinhoag** [comment]
When you wrote "it would be possible to do gaussian blurring in Neuroglancer" is this something you can toggle in the client's UI? Or were you referring to modifying the shader code to do this?

**Comment by jbms** [comment]
I meant that it could be implemented --- it is not currently implemented.
