### ISSUE TITLE
Multispectral images Rendering

### ISSUE THREAD

**Issue by tuffr5** [google/neuroglancer#240]
Hello, I got a problem when I tried to render an image that has more than 3 channels (not rgba). Is there a way for neuroglancer to render multiple-channels images like ImageJ. The image file (.tif) is in 'composite' mode.

What shader should I use? Since emitRGB is not working.

Thanks for your work.

**Comment by jbms** [comment]
Neuroglancer can handle multi-channel images in three ways:

If the channel dimension name ends with `^`, e.g. `c^`, then the shader can access that channel dimension directly, via. getDataValue(0), getDataValue(1), getDataValue(2), etc.  However, this is only supported if the data source can provide this dimension unchunked (i.e. chunk size is equal to the full extent of the dimension).

If the channel dimension name ends in `'`, i.e. `c'`, then the channel dimension is treated as a layer-local dimension.  In this case the shader only receives a single channel at a time, and you adjust the channel using the control in the layer tab.

Otherwise, the channel dimension will be treated just like any other dimension.

Can you say a bit more how emitRGB is not working?

**Comment by tuffr5** [comment]
Hi, thanks for replying.

I think my images are unchunked. I attached two images with different numbers of channel and also my python script. Hope that can illustrate my problem clearer. Thanks so much.

Following attachments in zip file:
[test_data.zip](https://github.com/google/neuroglancer/files/5152655/test_data.zip)

-- A0.tif (4 channels image)
-- A1.tif (3 channels image)
-- *.py (my script) 

The 3-channel image works fine with the setting of "emitRGB()  and C^". But I haven't found a way works for the 4 or more channels.

**Comment by jbms** [comment]
The issue with the 4-channel image is that it is a uint16 image, but the values are all in the 0-255 range, so it all appears as black with the shader you are using.  You need to change the shader to rescale the values, e.g.:

```glsl
void main() {
  emitRGB(vec3(toNormalized(getDataValue(0))*256.0,
               toNormalized(getDataValue(1))*256.0,
               toNormalized(getDataValue(2))*256.0));
}
```

**Comment by tuffr5** [comment]
Thanks. I tried to rescale the values to [0,255]. But it gave me like this:
![image](https://user-images.githubusercontent.com/31501302/91775421-9e403180-ebb0-11ea-9b55-628ecf37fe8c.png)

How should I work with the additional channels to display a colorful image in the browser?

If you happen to ImageJ, the image looks like this in ImageJ:
![image](https://user-images.githubusercontent.com/31501302/91775541-ee1ef880-ebb0-11ea-94de-02e7a0cefebe.png)

**Comment by jbms** [comment]
The shader I posted in the previous comment works for me:

![screenshot-shader](https://user-images.githubusercontent.com/4211946/91775820-e9524880-eba0-11ea-8d6a-ff8a622e6bdd.png)

**Comment by jbms** [comment]
Note: Only scale A0.tif (16-bit) by 256 --- A1.tif is already 8-bit and scaled appropriately.

**Comment by tuffr5** [comment]
I see. I'm ok to reproduce your display. Two more questions, does that getDataValue(0) mean that axis=0 is used? If so,  that axis=3 makes no contribution to the display? If further 5 or 6 channels images are used, what about other dimensions? Only the first 3 channels are used? Correct me if I am wrong. Many thanks.

**Comment by jbms** [comment]
getDataValue(0) returns the value with c^=0
getDataValue(2) returns the value with c^=2

You can access the values with c^=3, 4, etc. and it is up to you to decide how you want to map the data to RGB or RGBA.

**Comment by luhuifang** [comment]
Hello, I tried to render a single-channel image from multiple channels of data in the way discussed above, and encountered a new problem.

I have an 11-channel Zarr data, and each channel store a gene expression heatmap (the channel dimension is unchunked and its name ends with ^). When I try to render a single channel image in Neureoglancer, the displayed image is always incomplete. 

<img width="1440" alt="截屏2021-08-19 下午2 28 33" src="https://user-images.githubusercontent.com/28702459/130022001-2803831b-117c-41c4-ad49-cdc64378812d.png">

<img width="1440" alt="截屏2021-08-19 下午2 29 14" src="https://user-images.githubusercontent.com/28702459/130022081-f8bef37c-e1b2-45f6-be56-68917a32014e.png">

Following is my data file:
[FP200000474BL_B3_bin50_genes_10_zarr.zip](https://github.com/google/neuroglancer/files/7012369/FP200000474BL_B3_bin50_genes_10_zarr.zip)


May I have to know how to solve this problem? Thanks.

**Comment by luhuifang** [comment]
Sorry, the data I attached before was chunked, the data below is unchunked.
[FP200000474BL_B3_bin50_genes_10_zarr_unchunk.zip](https://github.com/google/neuroglancer/files/7043243/FP200000474BL_B3_bin50_genes_10_zarr_unchunk.zip)

Thanks.

**Comment by jbms** [comment]
The problem is that your dataset exceeds the GPU memory limit (defaults to 1GB).  Neuroglancer needs to store chunks that are displayed uncompressed in GPU memory.  You can adjust the GPU memory limit using the Settings panel (Gear icon at top right), but if you set it too high (more than about 2GB), the tab will crash.

The best way to reduce the memory requirement is to create downsampled levels --- that way when you zoom out neuroglancer will be able to use the downsampled levels which will greatly reduce the amount of data that must be kept in GPU memory.

Unfortunately the zarr datasource currently does not support multi-resolution data.  You can instead use n5 or precomputed format, though.

**Comment by jbms** [comment]
Note: You can see the GPU memory required by the visible chunks from the "Chunk statistics" panel.  Press "\" (backslash) to open it.

**Comment by luhuifang** [comment]
OK, I got it, thanks.
