### ISSUE TITLE
How to wrap displayDimensions property in python?

### ISSUE THREAD

**Issue by tuffr5** [google/neuroglancer#252]
Hi,
The displayDimensions property seems inaccurate when I was displaying a image in the order of ['z', 'y', 'x']. e.g., The layout of yz is actually xy plane. Is there a way to send the parameters from python? Or there is something important I didn't notice.

Thanks

**Comment by jbms** [comment]
The xy/yz/xz layout names are somewhat badly named; I picked those names back when Neuroglancer only supported an "xyz" coordinate space.  In those layout names, "x" just means the first display dimension, "y" means the second display dimension, "z" means the third display dimension.  Potentially it would make sense to have the layout names reflect the actual dimension names, but that is a bit complicated since the dimension names can change and there can be fewer than 3 display dimensions, in which case it would be unclear how to name the layouts.

One workaround is to ensure your display dimensions really are "x" "y" "z", which you can set from Python with: `state.render_dimensions = ["x", "y", "z"]`

**Comment by tuffr5** [comment]
Yes, that's complicated for layout. But it is really weird to see the layout name unmatched to the real one, right? I tried to set render_dimensions, however, it didn't work out.

Code:
> with viewer.txn() as s:
>     s.render_dimensions = ['x', 'y', 'z']

**Comment by jbms** [comment]
Yes, it is unfortunate that the layout name does not match the dimension names.

It turns out there was a bug in the Python bindings, which is now fixed (you will have to update to version 2.12 or install from the git repository).

The correct property is `display_dimensions`, not `render_dimensions`.
