### ISSUE TITLE
Sample NIFTI file comes up with no data

### ISSUE THREAD

**Issue by sevaa** [google/neuroglancer#257]
I'm trying to display a sample NIFTI file. I've downloaded the latest master, started the dev server with `npm run dev-server`. I've copied the attached file into the project root, and added the following source: `http://localhost:8080/vol-uint8.nii`. A quadruple of panels comes up, but there's nothing there, as if the file was all transparent voxels.

Additionally, not sure if it matters, the `uint8-volume` line in the right pane appears checked but stricken-through. usually that indicates a problem. In the browser console, there's a bunch of "Uncaught (in promise) null" messages.

Tried viewing under ImageJ, the file contains data. What am I missing, please?

Windows 10 v1909 x64, Chrome 85.0.4183.83 (Official Build) (64-bit), Node v12.18.3. Neuroglancer code from master from about a month ago.

[vol-uint8.zip](https://github.com/google/neuroglancer/files/5459897/vol-uint8.zip)

**Comment by jbms** [comment]
There was previously a bug whereby layer type auto-selection did not work for certain data sources, including nifti.  It was necessary to manually select the layer type as "image" or "segmentation":

![layer_type](https://user-images.githubusercontent.com/4211946/97605712-32b9eb00-19cc-11eb-8758-375ef9f5dcfe.png)

That was fixed by this commit: 8ff58354757f6701a6bc9d4e45a611743facae6b

Now, when you enter the path to a nifti data source, you are prompted to create it as an image layer, which you can do by clicking on the "Create as image layer" button at the bottom of the side panel or by pressing enter again in the data source URL field.

**Comment by sevaa** [comment]
Confirmed, with the latest code there's the yellow button "Create as image layer".
