### ISSUE TITLE
Bogus websocket traffic

### ISSUE THREAD

**Issue by sevaa** [google/neuroglancer#258]
I have a server where Neuroglancer dev-server is running on http://localhost:8080/. On the same server, there's another Web service on port 80 that is reverse proxying a directory - http://myserver/neuro/ - to http://localhost:8080/. Neuroglancer in that folder works as expected.

On my local machine, I also have the dev-server listening on http://localhost:8080/.

Now, when Neuroglancer from http://myserver/neuro/ is loaded and running in Chrome, **I see a lot of bogus traffic in the Network pane of the dev tools**. Looks like Neuroglancer is repeatedly trying to hit two websockets endpoints:

 - http://localhost:8080/sockjs-node/info?t=1604069002283
 - ws://localhost:8080/sockjs-node/029/wfvgkukx/websocket

Neither of those can be expected to work, since it's obviously hitting my local machine instead of the server, but why do those requests exist in the first place? The only mention of sockjs (ergo websockets) in Neuroglancer code that I can see is in the dev-python bits, and that's not what's running.

**Comment by jbms** [comment]
webpack-dev-server uses sockjs (which uses websocket) in order to implement its automatic reload functionality when it rebuilds due to source code changes; it does this by injecting some extra sockjs code into the Neuroglancer client.  I'm not sure exactly what your use case is, but if you don't care about that functionality, you can just ignore that traffic.  If you just build the Neuroglancer client via the build or build-min rules, and then serve the contents of dist/dev or dist/min directly with your web server, then webpack-dev-server won't be used and you won't get that traffic.
