### ISSUE TITLE
Hovering action or show another cursor

### ISSUE THREAD

**Issue by xxzhongUofM** [google/neuroglancer#281]
I have two similar images side by side and I want to have another cursor that tells me where I am on image2 when I hover over image1 and vice versa. Does neuroglancer have something similar built in? If not, I am thinking of using a hovering action to create my own hover function, but I can't seem to find the right keyword for it (tried mouseup0 but that only works after I clicked down first)

**Comment by jbms** [comment]
I assume you have a tiled view, where you have one dataset on one side of your screen and the other dataset on the other?

Currently having a shared cursor as you want isn't directly supported.  It could potentially be added.  Currently there are some workarounds though: the center position (indicated by the red/green/blue axis lines) is shared (unless you unlink position for the layer groups), so you can kind of use that as a shared cursor by dragging around the center position.

You can also create an annotation point in an annotation layer that is included in both layer groups, and then drag that around with alt+mousedown0, see example below:

[Example](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B3125.999755859375%2C3438.166748046875%2C4045.500244140625%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:8192%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/flyem_fib-25/image%22%2C%22tab%22:%22source%22%2C%22name%22:%22image%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/flyem_fib-25/ground_truth%22%2C%22tab%22:%22source%22%2C%22name%22:%22ground_truth%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%7B%22url%22:%22local://annotations%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%7D%7D%2C%22tool%22:%22annotatePoint%22%2C%22annotations%22:%5B%7B%22point%22:%5B3159.166259765625%2C3283.166748046875%2C4045.500244140625%5D%2C%22type%22:%22point%22%2C%22id%22:%2246f33226a1da114d0393d5a63916271d4ecdc026%22%7D%5D%2C%22name%22:%22annotation%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22annotation%22%2C%22visible%22:true%7D%2C%22layout%22:%7B%22type%22:%22row%22%2C%22children%22:%5B%7B%22type%22:%22viewer%22%2C%22layers%22:%5B%22image%22%2C%22annotation%22%5D%2C%22layout%22:%22xy%22%7D%2C%7B%22type%22:%22viewer%22%2C%22layers%22:%5B%22ground_truth%22%2C%22annotation%22%5D%2C%22layout%22:%22xy%22%7D%5D%7D%2C%22selection%22:%7B%22layers%22:%7B%22annotation%22:%7B%22annotationId%22:%2246f33226a1da114d0393d5a63916271d4ecdc026%22%2C%22annotationSource%22:0%2C%22annotationSubsource%22:%22default%22%7D%7D%7D%7D)

I would suppose that a built-in hover cursor feature  as you are requesting would display pretty the same way, just that you wouldn't have to explicitly add the annotation layer or explicitly drag it.

If you are trying to add this feature through the Python integration, note that the Python integration does not currently support mouse movement events -- only clicks.  I think trying to manage this through Python may be problematic though due to latency.

**Comment by xxzhongUofM** [comment]
Thanks for the reply! It's a shame hover isn't supported, but I was able to do it through the chrome console. Thanks!
