### ISSUE TITLE
Neuroglancer AWS S3 input

### ISSUE THREAD

**Issue by mzouink** [google/neuroglancer#292]
I want to load N5 file from S3 using the public URL to Neuroglancer but didn’t work for me. always "HTTP error 0: Network or CORS error."

**Comment by xgui3783** [comment]
Sounds like you might need to configure the CORS header on the bucket?

**Comment by mzouink** [comment]
ok thanks, the problem fixed. helper Link: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html

**Comment by danielsf** [comment]
@mzouink May I ask what specific configuration you used? Configuring my bucket with 
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "Content-Type",
            "Range"
        ]
    }
]
```
still results in "HTTP error 0: Network or CORS error".

**Comment by jbms** [comment]
Check the Chrome developer tools, specifically the Network tab, for more info on the CORS error.

**Comment by danielsf** [comment]
So... I haven't dug deep enough to completely understand the problem, but I'm going to write the solution here so that the next person who googles it might find it.

The problem appears to have been the region the bucket was created in. Originally, I created a bucket in us-west-2. neuroglancer could not find this bucket. I created an identical bucket in us-east-1 and everything "just worked." I suspect it has something to do with how AWS resolves bucket URLs. I'll open an issue when I know what I am asking for.

Anyway, here is the "Bucket Policies" JSON that worked for me (it might actually be more permissive than is necessary)

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::sfd-eastern-bucket/*"
        },
        {
            "Sid": "PublicReadGetObjectVersion",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObjectVersion",
            "Resource": "arn:aws:s3:::sfd-eastern-bucket/*"
        },
        {
            "Sid": "PublicListObjectVersions",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:ListBucketVersions",
            "Resource": "arn:aws:s3:::sfd-eastern-bucket"
        },
        {
            "Sid": "PublicListObjects",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::sfd-eastern-bucket"
        },
        {
            "Sid": "PublicLocation",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::sfd-eastern-bucket"
        }
    ]
```

and here is the CORS JSON (shamelessly copied from https://github.com/seung-lab/cloud-volume/wiki/Setting-up-Amazon-S3)

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 600
    }
]
```
