### ISSUE TITLE
Error in worker when restoreState is invoked while state already exists

### ISSUE THREAD

**Issue by timblakely** [google/neuroglancer#30]
Spinning up a local instance and going to [this link](http://localhost:8080/#!{'layers':{'image':{'type':'image'_'source':'precomputed://gs://neuroglancer-public-data/flyem_fib-25/image'}_'ground-truth':{'type':'segmentation'_'source':'brainmaps://274750196357:janelia_fib_25:groundtruth_roi_masked_by_binarized_eroded_2_cc'_'skeletons':'brainmaps://274750196357:janelia_fib_25:groundtruth_roi_masked_by_binarized_eroded_2_cc/skeletons'_'segments':['5643050'_'3054627'_'2984211']}}_'navigation':{'pose':{'position':{'voxelSize':[8_8_8]_'voxelCoordinates':[3219.05224609375_3359.037353515625_4045]}}_'zoomFactor':2.126423672711415}_'perspectiveOrientation':[0.7237077951431274_0.023455655202269554_-0.37096938490867615_0.5814452171325684]_'perspectiveZoom':90.46834404886944}) works. However, changing the state without a full refresh (e.g. removing least significant digit of zoomFactor) causes the following error:

`backend.ts:26 Uncaught TypeError: Cannot read property 'visibilityCount' of undefined
    at RPC.<anonymous> (backend.ts:26)
    at RPC.target.onmessage.e (worker_rpc.ts:104)`

It appears it's coming from [this line](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/shared_visibility_count/backend.ts#L26) in the shared visibility code. Discovered this while trying to do Viewer.state.restoreState with a modified state.

Possibly related: inspecting RPC.objects after restoreState shows that there are a number of duplicate entries for SharedUint64DisjointSets and Uint64Sets. Not sure if that's intended

**Comment by jbms** [comment]
Thanks for reporting this.  It turned out to be due to a reference counting bug.  Unfortunately the reference counting in Neuroglancer is tricky to get right because Javascript doesn't permit smart pointers, move semantics, etc. like in C++.  It might be possible to use identity type aliases to make things a bit more self-documenting --- not sure if that would cover all of the cases though.  There also aren't really any unit tests of the reference counting.
