### ISSUE TITLE
Question regarding loading large number of meshes

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#309]
I notice that when loading meshes, the Chunk Statistics tab shows that the visible chunks GPU memory fills up with all the fragments for `type: precomputed/MultiscaleMeshSource` before they then appear on screen and in the Statistics tab under `type: mesh/MultiscaleFragmentSource`. When I have thousands of meshes, the first part can take a considerable amount of time, so nothing is displayed for a while. Is there any way to speed it up or have it staggered so that meshes are displayed on a first come first served basis?

**Comment by jbms** [comment]
I agree that the current behavior does not seem ideal, but I'm not sure how to improve it.

Neuroglancer manages all data via a chunk abstraction.  Chunks are assigned a numerical priority that determines the order in which they are downloaded and the order in which they are evicted from memory to make room for higher priority chunks.

For meshes there is a single manifest chunk per segment and then one chunk per fragment.  The manifest chunks for selected segments have a fixed priority that is higher than all other priorities, since the mesh can't be displayed without it, and it is small.

This means though that all manifest chunks are downloaded before any mesh fragments or other data.

I suppose it might be preferable to see some mesh fragments sooner, and some volumetric data sooner.  But I'm not sure exactly how to formulate such a policy that leads to a well-defined and consistent result.

I think it could be problematic if the download order is not based on the same priority used for evicting from memory.

**Comment by davidackerman** [comment]
That makes sense. Thanks for clearing it up!

Regarding mesh visualization, is there a way to use different shading, ie flat shading? Rather than having lighting values interpolated over a face based on its vertices, having a single lighting value calculated for a face could enable production of simpler meshes. This is because one could greatly reduce the number of triangles determined from eg. marching cubes if one does not need to maintain vertices at the borders between planar parts of the mesh. To a flat shader, a planar region will look identical regardless of how many triangles comprise it (so long as it is fully triangulated), whereas smooth shading would look increasingly poor at the borders between planar regions as the number of triangles decreases. In short, flat shading could enable the same actual detail in a mesh using much fewer faces/vertices, at the cost of smoother shading.

**Comment by jbms** [comment]
There currently aren't options for controlling how the mesh shading is done.  Potentially they could be added.  In general neuroglancer mesh rendering is based on the assumption that the mesh is an approximation for visualization purposes only and does not perfectly match the surface.

If you want small meshes that look reasonably good, I would suggest the following approach (which is what we use):
1. For each level of detail, downsample the original segmentation to the desired scale, in a way that preserves segment ids (meaning that you consider a downsampled voxel to contain a given segment id if any of the full-resolution voxels in it contain the segment id).  This does mean segments are no longer guaranteed to be disjoint at the downsampled levels.  The advantage of this over e.g. striding based downsampling is that you don't disconnect objects, and the topology tends to become simpler as you downsample more.  Even for the finest mesh level I would recommend some amount of downsampling (e.g. if your initial data is 8x8x8nm, maybe downsample to 16x16x16 for your first level of detail), and then additional 2x2x2 downsampling for each successive level of detail.
2. Run marching cubes separately for each level of detail on the appropriate downsample scale.
3. Run mesh simplification, e.g. quadrics error-based vertex removal, on each mesh produced by marching cubes.  Note that if you just try to start with the finest level of detail mesh, and try to simplify the mesh further to get to a coarser level-of-detail, that doesn't tend to work well.

**Comment by davidackerman** [comment]
Thanks for all the info! I think I have been too overzealous in attempting to use meshes to perfectly capture the underlying surface, rather than as more of a visualization tool.

I have been doing some of the steps you have suggested, but will definitely look into those I haven't done yet. 

My results have been useful so far, albeit a bit memory intensive. I think with what you have suggested, I can reach a good balance of visualization speed and representation accuracy.

Thanks again for your responsiveness and advice!
