### ISSUE TITLE
Compiling draco with newer versions of emscripten leads to various errors (memory out of bounds)

### ISSUE THREAD

**Issue by chrisj** [google/neuroglancer#321]
Connected to https://github.com/google/neuroglancer/pull/317 but didn't want to clog up that discussion

`trzeci/emscripten` is currently deprecated in favor of `emscripten/emsdk` but I tried to find the latest version of `trzeci/emscripten` that I could get to work since I don't have a good understanding of WASI and also how you generated the `imports` object. I added empty stub functions for various wasi calls which silenced a lot of errors but eventually I ran into memory out of bounds.

The current code currently only compiles, at least on my end, using `build.sh` by tagging `trzeci/emscripten` to `sdk-tag-1.38.30-64bit`. It will compile up to `trzeci/emscripten:sdk-tag-1.38.45-64bit` by changing `WebAssembly.Table` initial and maximum from 368 to 374.

`sdk-tag-1.38.45` is the first version that gives me a memory out of bounds error as well as an error code 1 from `neuroglancer_draco_decode`

Also, if you decide to try various versions of `trzeci/emscripten`, you will run into issues using the upstream and fastcomp versions since there was a pwd change that wasn't fixed until 1.39.2. This causes `/emsdk/entrypoint: ./build_wasm.sh: not found`

Figured you might have more luck than me, especially since I'm not sure how you generated/chose values for the imports object.

**Comment by jbms** [comment]
This is related to the wasm issues described here: https://github.com/google/neuroglancer/pull/318

The existing content in index.ts was derived from the js file auto-generated by emscripten, but with unnecessary code removed in order to significantly reduce the size.  However, it does seem that resulted in some constants that may be dependent on the compiler version and code being compiled being hard coded.

I will look into how to fix this to compile with the newer toolchain and avoid hard coding constants.

**Comment by chrisj** [comment]
`STANDALONE_WASM` was added in `1.38.46` which seems like it should be relevant.
