### ISSUE TITLE
Parse segment query only when a key is pressed

### ISSUE THREAD

**Issue by hash-ir** [google/neuroglancer#330]
Hi,

I have created an action handler in Python which captures the state change based on the segment query. I am using regular expressions to get different object types. The problem is the up-gradation of the segment query as soon as I type a property that matches my regular expression e.g `prop > 6` is matched and the result is processed even though I wanted to write `prop > 60`.

I first tried creating a keyboard event listener in Python but it would be of no use since the segment query is being changed from the frontend (typescript). Basically, I want to turn off the auto-changing of the segment query and only use the enter key to do so. I noticed that Neuroglancer is also using a `KeyboardEventBinder` for the `queryElement`. Then, I tried commenting out two `registerDisposer(observeWatchable())` blocks in [segment_list.ts](https://github.com/google/neuroglancer/blob/49432e9d8debc0e23cdf6bf533d809c1b7fe5182/src/neuroglancer/ui/segment_list.ts#L816) but that didn't work. 

I reckon it would be a very small thing to change or add in the typescript files. However, I don't have any working knowledge of typescript. Any suggestions would be appreciated!

Best,
Hashir

**Comment by jbms** [comment]
Neuroglancer itself does some amount of "debouncing" when setting the segment query in the state as you type (meaning if you type quickly, it won't update the state until you pause typing).  Currently the enter key serves a different purpose --- it toggles the visibility of the segments that match the query.

Currently there isn't a way to configure the behavior to be what you want, exactly.  Another option would be to implement your own debounce logic in Python, so that you aren't recomputing the results too often.

If you describe more what you are trying to do that I might be able to suggest a better option.  I'm guessing that once the query matches your pattern, you compute the results and then overwrite the query with the list of matching segment ids?  I can see how that would be problematic.  In that case, though, one hacky solution might be to require a special character, like "!" or ".", to indicate the end of your query.   A better solution might be to introduce a proper mechanism in Neuroglancer for the Python backend to support segment queries.

**Comment by jbms** [comment]
If you haven't already seen it, you might want to take a look at how the segment query is designed to be used with properties specified in the precomputed json format:

[Example link](https://h01-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B3.3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B319924.96875%2C220681.515625%2C5027.1953125%5D%2C%22crossSectionScale%22:27.733853322530315%2C%22projectionOrientation%22:%5B0.2250797152519226%2C-0.0963120386004448%2C-0.04986383020877838%2C-0.9682854413986206%5D%2C%22projectionScale%22:808000.7320899689%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/4nm_raw%22%2C%22tab%22:%22source%22%2C%22name%22:%224nm%20EM%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%7B%22url%22:%22precomputed://gs://h01-release/data/20210601/c3%22%2C%22subsources%22:%7B%22default%22:true%2C%22bounds%22:true%2C%22properties%22:true%2C%22mesh%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22precomputed://gs://lichtman-h01-49eee972005c8846803ef58fbd36e049/goog14r0s5c3/segment_properties%22%5D%2C%22tab%22:%22segments%22%2C%22colorSeed%22:1661112272%2C%22name%22:%22c3%20segmentation%22%7D%5D%2C%22showAxisLines%22:false%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22col%22:1%2C%22size%22:378%2C%22visible%22:true%2C%22layer%22:%22c3%20segmentation%22%7D%2C%22layout%22:%223d%22%2C%22selection%22:%7B%22row%22:0%2C%22visible%22:false%7D%7D)

**Comment by hash-ir** [comment]
This is very good. I am also thinking of doing something similar!

What do you mean by the "precomputed json format"? Also, can I specify my own set of categorical and numerical properties in the Python backend? or will I have to change the frontend for this?
