### ISSUE TITLE
[video recording] Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by jingpengw** [google/neuroglancer#377]
thanks to all the contributors to make this great tool!

I am trying to make a video recording using the `video_tool.py`, but got an error:
```
tool$ python video_tool.py --bind-address 0.0.0.0 render wasp_seg.txt 01_sp1
2022-02-17T10:3144.335761 [0.000/    5] Requesting screenshot
http://my-server-address:34167/v/b10628cc4017f9bc0c87bb624953d09d326c95fa/ - Failed to load resource: the server responded with a status of 404 (Not Found)
Browser unresponsive, reloading
```

I have tried to manually install `Neuromancer` and all the unit tests have passed.

**Comment by jingpengw** [comment]
Thanks for your quick response.

I got the same error if I don't use the `--bind-address`.
```
(cf) tool$ python video_tool.py render wasp_seg.txt /mnt/home/jwu/Videos/01_sp1
2022-02-17T14:5649.392161 [0.000/    5] Requesting screenshot
http://127.0.0.1:37553/v/df2b39524095f6e4118de701ae5a8932e4fbfcdc/ - Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by jbms** [comment]
I think the 404 error is actually because you are missing the client HTML/JavaScript/CSS files.

These are generated as part of the setup procedure, but if you just run video_tool.py directly from the source repository they may not be found.

I think you can resolve the problem by installing the Neuroglancer python package properly, e.g. with `pip install neuroglancer` or `pip install -e .` (from the root of the repository), and then running `video_tool` via `python3 -m neuroglancer.tool.video_tool`.

**Comment by jingpengw** [comment]
thanks a lot! Following your suggestions, it is working now!
