### ISSUE TITLE
Question: How do you launch an NG instance from a web application and keep it alive (flask)?

### ISSUE THREAD

**Issue by Lauenburg** [google/neuroglancer#386]
**Background**
I am building a Flask app for proofreading instance annotations of 3D medical data. The main view shows a grid of images. Each image is the middle slice of an instance subvolume with the corresponding annotation layered on top. 

**Goal**
I want to enable the user to better evaluate the segmentation if he is unsure how to judge a label's quality (good, insufficient, uncertain).
Therefore, I would like to add a button that opens the whole 3D volume at the object's current position in the Neuroglancer (NG). 

**Issue**
Since all python examples require starting NG in interactive mode, I don't understand how to open an NG instance from within the Flask script and keep it alive.  

I made it work using a subprocess:
```python3
  @app.route('/neuro')
  def neuro():

      cmd = "python3 -i neuro_glancer.py --port 9015 --imgs "+str(source_path)+" --segs "+str(target_path)
      proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, universal_newlines=True)
  
  return redirect('http://localhost:9015/v/MyToken/', 301)
``` 
However, this solution is hacky and runs into multiple issues down the line.

**Comment by jbms** [comment]
The examples are run with in interactive mode so that Python stays running (as otherwise the web server will be unavailable) and so that you can use the interpreter shell to interact with the Neuroglancer API.  If you already have an existing web server that will stay running, you don't need to use interactive mode.

You should specify `allow_credentials=False` when creating the VIewer object.

**Comment by Lauenburg** [comment]
Thanks for the answer! So far I my scripts call `neuroglancer.Viewer()` after setting up the IP and port using `neuroglancer.set_server_bind_address(bind_address=ip,bind_port=port)`. `neuroglancer.Viewer()` creates and starts an independent Server instance. How can I get Neuroglancer to use the running web server - do I need to touch `server.py` for this, or has this use case already been considered by someone?

**Comment by jbms** [comment]
Currently there is no support for using an existing web server --- Neuroglancer always starts its own Tornado server.  The simplest workaround would be to have Neuroglancer listen only on localhost and set up your existing web server to proxy requests to the Neuroglancer web server.

In principle you could modify `server.py` to somehow work with an existing web server but that will probably be a lot more trouble.

Another option is to export the data in a format that Neuroglancer can read directly --- then you can just serve the data as normal static files and can use the `neuroglancer.ViewerState` API to generate static links.  That way you won't need the Neuroglancer web server at all.

**Comment by Lauenburg** [comment]
Splitting your answer into three subparts:

1. If I understand you correctly, this is how I currently solve the issue. I start Neuroglancer as an independent subprocess running its own Tornado server. I then have the app manipulate the `viewer.txn().position` based on the user's input and move the neuroglancer tap to the foreground.

2. This might be out of scope.

3. I am curious about this approach. I tried to wrap my head around it, but I am not sure I fully understand it. How I understand it:
    1. In a preprocessing step I could create a JSON-encoded read-only snapshot viewer state using `neuroglancer.Viewer().state`
    2. Subsequently I could create a publicly sharable URL to the viewer state using `print(neuroglancer.to_url(viewer.state))`

    In case that the above assumptions are correct:
        - Will this not start a webserver?
        - Is this a 2D or 3D view?
        - Is there any way/tool to create the static files except using Neuroglancer itself?

**Comment by jbms** [comment]
> Splitting your answer into three subparts:
> 
> 1. If I understand you correctly, this is how I currently solve the issue. I start Neuroglancer as an independent subprocess running its own Tornado server. I then have the app manipulate the `viewer.txn().position` based on the user's input and move the neuroglancer tap to the foreground.

It is not necessary to start a separate subprocess --- Neuroglancer can also run its own Tornado web server from the same process as your Flask web server.

> 2. This might be out of scope.
> 3. I am curious about this approach. I tried to wrap my head around it, but I am not sure I fully understand it. How I understand it:
>    
>    1. In a preprocessing step I could create a JSON-encoded read-only snapshot viewer state using `neuroglancer.Viewer().state`

You should use `neuroglancer.ViewerState()` instead --- that won't start a web server.

>    2. Subsequently I could create a publicly sharable URL to the viewer state using `print(neuroglancer.to_url(viewer.state))`
>    
>    In case that the above assumptions are correct:
>    - Will this not start a webserver?
>    - Is this a 2D or 3D view?

You can control the view layout with e.g. `state.layout = '3d'` or `state.layout = 'xy-3d'`.  But in order to view 3d meshes you need to have already generated 3d meshes.

>    - Is there any way/tool to create the static files except using Neuroglancer itself?

Unfortunately Neuroglancer itself does not include a tool for generating the static files.

If you just want to display cross sections of volumetric data, you can use zarr, n5, or neuroglancer_precomputed format (or even NIFTI).  There are various tools to write those formats --- notably tensorstore (https://github.com/google/tensorstore) and cloudvolume (https://github.com/seung-lab/cloud-volume) for Neuroglancer precomputed only.

If you want to display meshes, the only supported format is neuroglancer precomputed (and in that case it would be simplest to also use that format for the volumetric data).  Unfortunately we have not yet been able to release our own meshing implementation.  You might look into igneous (https://github.com/seung-lab/igneous) but I"m not sure how easily it can be used for small volumes.

**Comment by jbms** [comment]
I'm not sure exactly what sort of application this is, but if it is intended to support more than one browser / user at a time, then you may want to avoid a single global `Viewer` object, since then they will all be synchronized.  Instead you may want to use `neuroglancer.UnsynchronizedViewer` instead.  With `UnsynchronizedViewer`, the view state is encoded in the URL so every browser / user is independent.

**Comment by Lauenburg** [comment]
I think, for now, it only serves as a single-user app. But I will discuss it with the team and test it out anyways. Thank you!

**Comment by Lauenburg** [comment]
**A quick off-topic question:** Could you direct me to the part in your code or the corresponding library that you use to directly pass NumPy data from the backend to the frontend? I currently use `h5wasm` and `mathjs` to avoid having to cache individual 2D image sections from a 3D image volume (saving them as PNGs using python and reloading them in the frontend). But obviously, you have a much more efficient approach to delivering the data to the frontend.

**Comment by jbms** [comment]
The relevant code for the browser is here:

https://github.com/google/neuroglancer/tree/master/src/neuroglancer/datasource/python

On the Python side it is here:

https://github.com/google/neuroglancer/blob/5787d018c2dbf9804fefb2da73a7c37a49b89842/python/neuroglancer/server.py#L315

**Comment by Lauenburg** [comment]
Thank you! I will study that.
