### ISSUE TITLE
File loads from GUI, but not URL

### ISSUE THREAD

**Issue by ChaiaEran** [google/neuroglancer#478]
I'm working with a localhost test environment of Neuroglancer, and I'm trying to send NIFTI files from my localhost build of my web app to the localhost Neuroglancer environment, but sending the filepath via `http://localhost:8080/#!nifti://localhost/`+`my file path` results in an "HTTP Error 0: Network or CORS error", even though inputting the exact same path into the GUI successfully loads the file. Is there something I'm doing wrong?

**Comment by jbms** [comment]
A few things:

- This syntax `http://localhost:8080/#!nifti://localhost/+my file path` is not correct for adding a datasource to Neuroglancer.  That is the syntax for loading a Neuroglancer JSON state from a URL.  The syntax for adding a datasource is more verbose --- the easiest way is to just add the data source using the Neuroglancer UI, and then look at the URL you end up with.  You can also use the Neuroglancer python package to construct a URL.

- You need to configure your web server to allow cross-origin requests (CORS), unless you use the same web server to also host Neuroglancer itself.   Since you say it works if adding the data source in the UI, perhaps you have already configured this correctly --- but in that case I don't know why you would have observed the error you saw.

**Comment by ChaiaEran** [comment]
Thank you! I definitely had the syntax wrong, this helped a lot!
