### ISSUE TITLE
Programmatically Changing Displayed Segments in a Segmentation Layer (JS)

### ISSUE THREAD

**Issue by dvanselow** [google/neuroglancer#479]
I'm developing an ontology traverser for a brain atlas, and I'm looking to programmatically change the displayed segments in a segmentation layer.

I've tried the following approach, but it's not working as expected:

`temp_state = viewer.state.toJSON();`
`temp_state['layers'][10]['segments'] = ['16429','18022'];`
`viewer.state.restoreState(temp_state);`

This call returns `undefined `and does not update the viewer state. It's liekly that I might be missing something obvious or taking the wrong approach. Any assistance in understanding how to correctly manipulate the segments would be greatly appreciated!

**Comment by stuarteberg** [comment]
Try this:


```python
with viewer.txn() as s:
    s.layers['my-layer-name'].segments = ['16429', '18022']
```

**Comment by stuarteberg** [comment]
Oops, that was an example for the Python API.  What language are you using?  If you're using TypeScript, then someone else will need to chime in.

**Comment by stuarteberg** [comment]
Your example code works for me, at least in my browser's developer tools console...

```javascript
temp_state = viewer.state.toJSON();
temp_state['layers'][1]['segments'] = ['26650', '11022'];
viewer.state.restoreState(temp_state);
```

(It does return `undefined`, but the viewer updates correctly.)

---

One thing to double-check: The index of the layer (e.g. `temp_state['layers'][10]` should NOT match what you see in the UI, since obviously the JSON `layers` list starts with item `0`, whereas the UI starts counting at `1`.  Are you sure you're updating the correct layer?  And be sure you're looking at the complete layer list (including "archived" layers, not just the ones shown at the top of the screen).

---

BTW, I notice that neuroglancer's own JSON editing UI also calls `reset()` before applying the new state, though I don't know why that's necessary:

https://github.com/google/neuroglancer/blob/5ccc518c5c6fa21a257d27805758eeac7d461fef/src/neuroglancer/ui/state_editor.ts#L95-L101

**Comment by dvanselow** [comment]
Ah! working! @stuarteberg - I had two state variables that were very close to the same name and was updating with the incorrect one. Was also thrown off by the `undefined` response. interesting about the `reset`.

This has to be the one of the most helpful, quickest replying community. Thanks much!

**Comment by dvanselow** [comment]
Ah! working! @stuarteberg - I had two state variables that were very close to the same name and was updating with the incorrect one. Was also thrown off by the `undefined` response. interesting about the `reset`.

This has to be the one of the most helpful, quickest replying community. Thanks much!

**Comment by ChrisRaven** [comment]
Just for future reference, if anyone would want to add or remove segments programmatically, without saving and restoring the JSON state, you can do this:

```
a = Uint64.parseString('720575941352499760')
viewer.selectedLayer.layer_.layer_.displayState.segmentationGroupState.value.selectedSegments.add(a)
// or
viewer.selectedLayer.layer_.layer_.displayState.segmentationGroupState.value.selectedSegments.delete(a)
// and to hide and show segments:
viewer.selectedLayer.layer_.layer_.displayState.segmentationGroupState.value.visibleSegments.add(a)
viewer.selectedLayer.layer_.layer_.displayState.segmentationGroupState.value.visibleSegments.delete(a)
```
