### ISSUE TITLE
z slices at multipes of 16 & 16+1 display the same image on Intel graphics

### ISSUE THREAD

**Issue by falkben** [google/neuroglancer#51]
In the X/Y view identical images are displayed at z values of 16/17, 32/33... (n * 16) / (n * 16 + 1) when using Intel integrated graphics.  The underlying intensities are loaded correctly, because the onhover data that is displayed corresponding to the image intensity changes with the different z values.  The x/z and y/z show different image data, it's just the X/Y view that doesn't update the image display.  When using a different graphics chip (Nvidia/AMD) the images display correctly at the different z slices.

I've seen this behavior on notebooks running Windows and MacOS using the intel graphics in Chrome, Firefox, and Safari.

**Comment by alexbaden** [comment]
I was able to partially reproduce using the precomputed data in one of the Neuroglancer demos. 
```
http://localhost:8080/#!{'layers':{'corrected-image':{'type':'image'_'source':'precomputed://gs://neuroglancer-public-data/kasthuri2011/image_color_corrected'}}_'navigation':{'pose':{'position':{'voxelSize':[6_6_30]_'voxelCoordinates':[5523_8538_0]}}_'zoomFactor':5.643278032499887}_'perspectiveOrientation':[-0.0040475670248270035_-0.9566215872764587_-0.22688281536102295_-0.18271005153656006]_'perspectiveZoom':340.35867907175077_'layout':'xy'}
```
On a desktop with a NVIDIA Quadro K5200 I see different sections for z-index 0 and z-index 1. On a laptop with a Intel Core i7-7700HQ (HD graphics 630) I see the same section for z-index 0 and z-index 1. The rest of the dataset is then "shifted" by 1 voxel in the z direction (so what is really slice 10 ends up as slice 11). 

Playing with the fragment shader, it looks like the problem could be here:
```
export const glsl_getPositionWithinChunk = `
vec3 getPositionWithinChunk () {
  return floor(min(vChunkPosition, uChunkDataSize - 1.0));
}
`;
```

By replacing all the texture lookups with an RGB color, I can determine whether or not the texture coordinates are changing between each slice. When I remove the `floor` wrapper around `min`, I get a change between slice `0` and slice `1`. Unfortunately I wasn't able to get any of the WebGL Inspectors going to actually look at the buffers (looks like `WEBGL_draw_buffers` does not play nice with any of the WebGL inspectors). 

I'm wondering if `floor` has different behavior on an Intel GPU than it does on Nvidia or AMD.

**Comment by jbms** [comment]
Thanks for looking into this Alex!  I am also able to reproduce it on a laptop with Intel HD Graphics 630, so I should be able to investigate it further.  Floating point issues like this have come up in the past, and I've added various bits of code to try to mitigate them, but each new GPU seems to have its own issues.  I think that WebGL2 will at least avoid a large fraction of these issues, by eliminating the use of floating point for integer operations.  However, I will have to look further to figure out the root cause here.

If you notice in the orthogonal views, by default, or when you type in a position explicitly, or when you press z,  z = 1 corresponds to the boundary between position 0 and 1, rather than the mid point of position 1.  This has certain advantages, but it also means there is no margin for floating point error as far as selecting the correct slice.

**Comment by jbms** [comment]
I think I've identified the root of the problem:

vChunkPosition = (position - uTranslation) / uVoxelSize;

In this example, uVoxelSize = vec3(6.0, 6.0, 30) and the (position - uTranslation).z is an exact multiple of 30.  Under IEEE 754, this would lead to an exact result.  However, the OpenGL ES Shading Language Version 1.00 specification states that division may be replaced by multiplication by the reciprocal, and that is problematic in this case because 1 / 30 cannot be represented exactly.  See https://www.khronos.org/files/opengles_shading_language.pdf page 57 (labeled as page 51 in the document).  Version 3.00 of the shading language (available in WebGL 2) also permits this.

I don't know of any way to force accurate division within GLSL, and even without this particular inaccuracy, there are still other ways that could lead to vChunkPosition being slightly off in the negative direction.

Therefore I think the best mitigation is to just add a small offset to vChunkPosition in the direction of abs(uPlaneNormal).  Just adding a small offset to all components of vChunkPosition, as Alex Baden suggested by email, also solves this problem, but offsetting within the viewport plane isn't necessary, and is slightly noticeable if you zoom in extremely far.
