### ISSUE TITLE
unify mesh source format

### ISSUE THREAD

**Issue by alexbaden** [google/neuroglancer#55]
It looks like there are two different fragment mesh formats currently being used:

Brainmaps: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/brainmaps/backend.ts#L212
Precomputed: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/backend.ts#L60

Does anyone object to changing the precomputed source to use the brainmaps format? Or, perhaps, adding a flag in the manifest to specify the source type? Opening this issue for discussion!

**Comment by jbms** [comment]
We can't just change the precomputed format, since that would break existing usage of it --- it would be inconvenient for everyone using it to have to recompute or convert their existing meshes.  We could extend the precomputed format to support options, though, if that is useful.  It probably makes sense to put the format information in info.json, unless you see a need for different formats on a per-object basis.

**Comment by alexbaden** [comment]
It looks like there are also some slight differences in the URL syntax for the manifest file. I guess there isn't a good way to determine which format is used for the fragment file based on the file... I suppose we could put an `IndexNumBytes` flag in the manifest. Not sure if it's worthwhile (vs just re-generating meshes or generating them ondemand).

**Comment by jbms** [comment]
Can you explain a bit more what your objective is regarding unifying the mesh formats?  Is it just to simplify the neuroglancer code a little bit?

**Comment by alexbaden** [comment]
No, we have meshes that are stored alongside a datasource that we would also like to look at using the precomputed format.

**Comment by jbms** [comment]
Probably the best thing to do is to add support for your mesh format to Neuroglancer, and add an additional option to the precomputed info file to specify the mesh format.

**Comment by alexbaden** [comment]
Perhaps I could add a `mesh_format` field and support `brainmaps32` and `brainmaps64` as options, with the default being `brainmaps32`?

**Comment by jbms** [comment]
I'm still not understanding what the specific use case is.  Is the issue that you have already generated meshes in the "brainmaps" format (i.e. what you are calling brainmaps64)?

**Comment by alexbaden** [comment]
Yeah, I have meshes with both types of headers: numVerts and numIndices as
uint32 or uint64 (though both have less than 2^32 vertices).

**Comment by jbms** [comment]
I'm sure we'll want to add other formats in the future (in particular https://github.com/google/draco), so adding an encoding field would make sense.  I guess putting it into the main info file wouldn't be great since you can also specify a mesh via a URL, so we would really need a new optional info file in the mesh directory that specifies the encoding.

However, in general the 64-bit format is not really useful since neuroglancer could never support anywhere close to 2^32 vertices or triangles in a single mesh fragment.  It seems like the only purpose of supporting this old format would be to avoid the one time cost of converting some of the meshes you already have (and if you wanted you could avoid remeshing, and simply modify the binary files directly).  Is it a large enough amount of data that doing so would be problematic?

**Comment by alexbaden** [comment]
Ok, that seems reasonable. We could probably just embed the encoding in the mesh manifest file. For now I'll use 32-bit headers in both the boss and precomputed datasources.
